# Generated by Django 5.0.6 on 2024-06-29 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('rating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='menu',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('owner', 'menu')},
        ),
    ]
