# Generated by Django 5.0.6 on 2024-06-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='owner_user',
        ),
    ]
