# Generated by Django 5.0.6 on 2024-06-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rename_owner_comment_owner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='menu',
            new_name='position',
        ),
    ]
