# Generated by Django 5.0.6 on 2024-06-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_rename_owner_user_comment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='position',
            new_name='menu',
        ),
    ]
